### ISSUE TITLE
Multipart request to create entity and content in single request fails with http 400

### ISSUE THREAD

**Issue by NielsCW** [paulcwarren/spring-content#1892]
**Describe the bug**
Performing a `multipart/form-data` request to the endpoint to create entity and content in single request fails with `400 Bad Request`

**To Reproduce**
- Perform a httpie request using `http --print HhBb --form <url> foo=bar content@test.txt`
- The server responds with a http `400 Bad Request`

The application fails at [this line](https://github.com/paulcwarren/spring-content/blob/main/spring-content-rest/src/main/java/org/springframework/data/rest/extensions/entitycontent/RepositoryEntityMultipartHttpMessageConverter.java#L46) because the `Content-Type` header has value `multipart/form-data;boundary=8c...37;charset=UTF-8`

**Expected behavior**
Succeeding to create entity with a `201 Created`

**Comment by tgeens** [comment]
Note there are 2 parameters appended to the `Content-Type`, which are not covered by spring-content mockmvc-based tests:

- `boundary=...` is appended by (any) httpclient, mockmvc does not, because it operates at a higher abstraction level
- `charset=UTF-8` is automatically appended by `OrderedCharacterEncodingFilter` (via `HttpEncodingAutoConfiguration`) in an auto-configuration scenario, but is not loaded via `MockMvcBuilders.webAppContextSetup(context).build()`
