### ISSUE TITLE
Breaking change from 1.0.0.M5 -> 1.0.0.M6 for JPA (postgres usage)

### ISSUE THREAD

**Issue by tspaeth** [paulcwarren/spring-content#197]
Hi!
I was just about to upgrade from 0.12.0 to the latest 1.0.0.M10 but discovered, that the postgres (so probably spring-content-jpa) connection has now issues... 

I'm getting this (excerpt) exception:
```java
org.postgresql.util.PSQLException: LargeObjects (LOB) dürfen im Modus 'auto-commit' nicht verwendet werden.
	at org.postgresql.largeobject.LargeObjectManager.open(LargeObjectManager.java:249) ~[postgresql-42.2.12.jar:42.2.12]
	at org.postgresql.largeobject.LargeObjectManager.open(LargeObjectManager.java:235) ~[postgresql-42.2.12.jar:42.2.12]
	at internal.org.springframework.content.jpa.io.PostgresBlobResource.getInputStream(PostgresBlobResource.java:61) ~[spring-content-jpa-1.0.0.M6.jar:na]
	at internal.org.springframework.content.jpa.repository.DefaultJpaStoreImpl.getContent(DefaultJpaStoreImpl.java:93) ~[spring-content-jpa-1.0.0.M6.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
```

I've nailed it down to the code changes in between 1.0.0.M5 -> 1.0.0.M6.
Before investigating too deep into all classes, configuration issues and dependencies - is this a well known problem?

Remark: It helps to set (Spring Boot 2.2 tested) 
```
spring.datasource.hikari.auto-commit=false
```
but that has other consequences in existing applications probably.

**Comment by paulcwarren** [comment]
There was a significant re-write of the spring content jpa module in that timeframe in order to support transactions.  

Previously, our database content streaming implementation was multi-threaded and unfortunately a Spring transaction is limited to a single thread.  Therefore, we had no choice but to refactor the implementation and, for postgres, that meant moving to their LOB API.  That cant be used in "auto-commit" mode because it stores the content over several records.   But without this refactor then you wouldn't get proper transaction support. 

Whether, or not, auto-commit is backward compatible or not is hard to say.  As I understand it,  "auto-commit" means that transactions have to be explicitly committed.  You cant rely on JPA to wrap database operations in a transaction for you.  If all of your database access is through Spring Data and/or uses the @Transactional annotation.  Or if any custom database code you may have added is explicitly in transactions then turning auto-commit off should be ok.

**Comment by paulcwarren** [comment]
Hi @tspaeth, was this information of any use?  Are you still stuck on this issue?

**Comment by tspaeth** [comment]
> Hi @tspaeth, was this information of any use? Are you still stuck on this issue?

No, not directly. The last days I pulled up another demo project based on the JPA demo. I've figured out, that, as soon as I add spring-data-envers, all queries get transactional - even in Readmode. That seems to be the reason when the autocommit for HikariCP has to be explicitly disabled. 
So, spring-content works "out of the box" when not using the auditing module. Just in case others stop by...

**Comment by paulcwarren** [comment]
Thanks @tspaeth.  That's good info.  

I haven't used that library personally but by the looks of it (from a quick scan of the docs) I think it makes sense for it to be transactional.  When using the revisions capability, when you save an entity, then spring-data-envers needs to stripe related information across a few different tables; the main entity table, the deltas tables and the revisions table.  Its not just upserting info into the main entity table anymore.  So, it needs an explicit transaction around all of that to ensure it all commits, or none of it commits.

and in that sense it is similar to postgres' LOB implementation actually as it also needs to stripe related information across a couple of tables.

So both need explicit transaction around all of those inserts/updates.

HTH

**Comment by paulcwarren** [comment]
Closing.  The issue was actually in the spring-data-envers library.  Please feel free to reopen if new information comes to light.
