### ISSUE TITLE
searchContent cause invoke Repository.findAll ,and will have performance issue

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#223]
http://localhost:8080/archives/api/v1/documents/searchContent?queryString=RocketMQ , first search contentId from elasticsearch , if Entity's id is not ContentId , will invoke invoker.invokeFindAll, please provide findByContentId or findByContentIds method to RepositoryInvoker

version: 1.0.0.M10

**Comment by paulcwarren** [comment]
@lmtoo this is currently true.  I am looking to refactor the identity to possibly contain the entity id (when appropriate) so that lookup can be done through the index that will inevitably be on the ID column.

The other alternative that I am considering is the one you mentioned where we look on the repository to see if it has been decorated with a findByContentId.
