### ISSUE TITLE
InputStream has bean copy too many times in main memery

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#258]
a way to access RandomAccessFile instead of InputStream in BeforeSetContentEvent.getInputStream or ContentStore's setContent to reduce file copy.

In method annotated by @HandleBeforeSetContent , itextpdf or pdfbox need RandomAccessFile to load huge file, like 1Gb , this means I need to save InputStream to local file system first , and pass this temp file to itextpdf or pdfbox,  at the same time , in a custom ContentStore which use  http to upload other store system , which need a md5 parameter, and in setContent's implementation I need also to save inputStream to local file system again, because setContent's second argument can't reopen, which I need first open to generate md5 , and the second open to transport this file.

**Comment by paulcwarren** [comment]
Hi @lmtoo, thanks for raising this issue.  

OK.  I think I understand you would like the `BeforeSetContentEvent` handler to provide a `RandomAccessFile` instead of an `InputStream`.  Similarly you would like `setContent` to take a `RandomAccessFile` instead of a `InputStream`.

And just for my information, it sounds like you have implemented your own ContentStore?  Can I ask for what storage?

**Comment by lmtoo** [comment]
It's a internal document storage service which delegate to mongodb/oss

**Comment by paulcwarren** [comment]
Thanks. 

I forgot one question...sorry...are you using Spring Content REST on top of this?

**Comment by lmtoo** [comment]
for now , that's true , but Spring Content REST can easily use another storage

**Comment by paulcwarren** [comment]
(WIP)
# Problem
Under some circumstances providing content as an inputstream, as we do today, can be inconvenient for event handlers and store customizations as it forces them to stream the contents into a file in order to process it in various ways.  This becomes very inefficient when the content is large and/or when the content needs to be processed several times.

The objective, then, is to provide a way for developers to implement an end-to-end customization that allows a rest call to be made that converts the uploaded resource/input stream into some other more convenient type, in this case a RandomAccessFile, invoke event handlers with that converted type and then invoke a storage method also with that converted type.  

# What Won't Work

- In hindsight what would have been nice is if we had made the ContentStore content type generic; i.e. `public interface MyStore extends ContentStore<MyDoc,UUID,RandomAccessFile>` .  However, it is not possible to add additional parameter types to an existing generic type.

- Adding additional store methods that use a different content type; i.e. `S setContent(S entity, RandomAccessFile file)`.  Whilst it is possible to add the methods, it is difficult to decide which of these to call from the REST interface.  

# Existing Capabilities

## Store Fragments

It is possible today to implement a StoreFragment that adds functionality to the Store.  Renditions and fulltext search are, in fact, implemented using StoreFragments.  However, we haven't ever used a fragment to override Store methods.  In general, overriding Store methods will work because fragments are evaluated first so it would be possible to add a StoreFragment with a method such as `MyDoc setContent(MyDoc, RandomAccessFile)`.  

However, what isn't possible at the moment:- 
- converting the content InputStream into a different type, as required by the overridden store method
- calling relevant event handlers for the overridden store method

## Spring Content REST

It is also not currently possible to export a StoreFragment method as a StoreResource.     

# Proposal

// TODO

**Comment by paulcwarren** [comment]
Hi @lmtoo 

I've been mulling this one over a fair bit.  I am unsure between Alternative 3 `BufferedContentStore` or Alternative 5 `Complimentary Interface`.  BufferedContentStore implies an *alternative* to ContentStore that looks like this:

```
	S setContent(S property, RandomAccessFile content);

	S unsetContent(S property);

	RandomAccessFile getContent(S property);
```

A complimentary interface, let's call it, BufferedContentStoreSetter implies an *optional addition* to ContentStore that looks like this:

```
	S setContent(S property, RandomAccessFile content);
``` 

Not sure which I like so I was wondering if you have a requirement, or see a need, for `RandomAccessFile getContent(S property)` at all?

**Comment by lmtoo** [comment]
no need `RandomAccessFile getContent(S property)` for now ,  BufferedContentStoreSetter is preferred

**Comment by paulcwarren** [comment]
Thanks for the update @lmtoo.  

Thinking about it If it is just one method we are after then actually I prefer just adding it to ContentStore and using the StoreRestResource annotation to configure which setter method the rest layer calls.  I added another alternative above.

**Comment by lmtoo** [comment]
ContentStore can split up to ContentSetter<I> and ContentGetter<O>, by default ContentStore inherit from  ContentSetter<InputStream> , If a custom ContentStore is needed, then a custom ContentStore can inherit from ContentSetter<RandomAccessFile>

**Comment by lmtoo** [comment]
Is `S setContent(S property, RandomAccessFile content);` can replaced by `S setContent(S property, Resource content);`?

**Comment by lmtoo** [comment]
Since from spring5.0 Resource has add a new readableChannel method , which can make use of zerocopy

**Comment by paulcwarren** [comment]
Yes, we can probably do something like this.  A Store is basically a generic Spring `ResourceLoader` actually so in some respects it makes sense to be able to set content with a Resource.  Funnily enough, when I added `AssociativeStore` I was considering making it `associate(S entity, Resource r)` instead of `associate(S entity, SID id)`.

But I was using `RandomAccessFile` as I thought you needed that for the event handlers that call itext/pdfbox.  Is a Resource OK for those?  Do their APIs support Channels as well as RandomAccessFile?

**Comment by lmtoo** [comment]
RandomAccessFile can create from a File ,If BeforeSetContentEvent.getInputStream replaced by BeforeSetContentEvent.getResource().getFile() , then RandomAccessFile can create from this, also itext/pdfbox can directly use a File as parameter

**Comment by paulcwarren** [comment]
OK.  This makes sense then.  Thanks for your input.

**Comment by paulcwarren** [comment]
Hi @lmtoo, 

This commit on head of 1.1.x has a first cut of this feature.  It is *incomplete* but none the less usable as it stands.  

It adds `ContentStore.setContent(S, Resource)` and adds the ability for the REST layer to resolve PUT/POST content requests to a single `setContent` method and convert the incoming InputStream from the client into a File-backed Resource when appropriate.  If you want to give it a try then update your spring-content dependencies to 1.1.M3-SNAPSHOT and un-export the `setContent(S, InputStream)`  method as follows:-

```
public interface MyContentStore extends ContentStore<MyEntity, UUID> {

  @org.springframework.content.rest.RestResource(exported=false)
  @Override
  MyEntity setContent(MyEntity entity, Resource r);
}
```

This will not export the InputStream variant of the method leaving only the Resource variant which will then be used to set content.

I know you want to use a threshold to decide when to use InputStream and when to use Resource so I plan to make make this configurable but I am not going to get to that for a week or so.  So, I wanted to give you something you could try.

HTH

**Comment by paulcwarren** [comment]
Hi @lmtoo.  

1.1.0.M3 is not released.  

You should be able to consume this functionality.  The docs for it are [here](https://paulcwarren.github.io/spring-content/refs/snapshot/1.1.x/rest-index.html#_putpost_content_handling).

Based on our conversations I believe that you want to use a threshold to determine when to use a Resource instead of an InputStream for setting content.  You should configure your application using the XYZ, as follows:

```
public interface ExampleStore extends ContentStore<Example, UUID>{}

@Configuration
public static class ApplicationConfig {

   @Bean
   public ContentRestConfigurer configurer() {
       return new ContentRestConfigurer() {
           @Override
           public void configure(RestConfiguration config) {

               config.forDomainType(YourEntity.class).setSetContentResolver(new Resolver<Method, HttpHeaders>(){

                @Override
                public boolean resolve(Method method, HttpHeaders context) {
                    // inspect the content-length header and based on that decide whether `method` is the correct one to use, 
                    // or not.  Return true if so, otherwise return false.
               }});
           }
       };
   }
}
```

I'm going to go ahead and close this but feel free to re-open if we didn't quite hit the mark.

**Comment by lmtoo** [comment]
hi @paulcwarren RenditionProvider need Resource version too.

**Comment by paulcwarren** [comment]
Yeah, indeed.  Its been on my todo list to convert RenditionProvider over to a Resource-based API so we can definitely do this. 
Can I ask how this is related to the above bug though as it seems unrelated to the addition of the new `setContent(S, resource)`?
