### ISSUE TITLE
codacy not active for wip/springboot2

### ISSUE THREAD

**Issue by LadislavSopko** [paulcwarren/spring-content#28]
hi paul
can you activate codacy for wip/springboot2 my PR not pass cause it is not active
thx
ladislav

**Comment by paulcwarren** [comment]
Hi Ladislav, thanks for this.  I will try and look at this soonest.  I am at a conference this week and away from my laptop for the most part so I just want to provide forewarning in case I don't.  At first glance the code looks fine.  Only thing I spotted so far was unnassociate.  It needs to check whether the @ContentId is not also the Spring Data @Id before nulling out the value otherwise we null out their Id as well which isn't good obviously.  But I can add this code.  In general it looks good.  

I am not sure what it takes to add codacy?  I'll look into it.

**Comment by paulcwarren** [comment]
Ok.  I enabled it.  Seems like there is some work to do :-|
