### ISSUE TITLE
Add timeout lock feature

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#327]
On web envirement , lock timeout is needed , because web browser may crashed or exit unpredictable, and web programe don't have the opportunity to unlock the document, and this well lead document locked forever unless lock user to unlock manually.

**Comment by paulcwarren** [comment]
Hmmm, ... yeah I think the real issue here is that the locking and versioning module internalizes its security concerns which is distinctly not very Spring-like.  

It would be more Spring-like to place rbac constraints on the lock/version/unlock REST endpoints or use method security on the LockingAndVersioningRepository methods.  This would allow the Developer to allow other "privileged" users to unlock documents when required.

The problem with that approach though is that it is more difficult to implement, I suspect.  More correct but more difficult.

In the meantime, perhaps a timeout is reasonable.  Would you imagine this is supplied by the user when they lock the document?

**Comment by lmtoo** [comment]
Hi, @paulcwarren  I disabled lock/unlock endpoints , as I found other ways to bypass this by alternative user interaction
