### ISSUE TITLE
Spring Display image that was just uploaded by the user without restarting the server

### ISSUE THREAD

**Issue by AhmedMohsenM95** [paulcwarren/spring-content#37]
i uploaded the project files so you can take a look at them, i only uploaded the related parts so it wont be too big
Edited:
[Project Files](https://ufile.io/ahvkg)

**Comment by paulcwarren** [comment]
Hi @AhmedMohsenM95.  I took a look at your project today.  There were a couple of issues.  Mainly to do with running as a WAR and not as a Spring Boot application.  I think in my SO post I was assuming you were using Spring Boot.  Anyways, here are the issues that I corrected:-
1. Update the form action to include the context path of the deployed web app; i.e. I deployed the web app to `/websocial` therefore I updated the form action on `index.jsp` to `/websocial/profilePic/profile1.jpg`, as follows:-

```
<form:form action="/websocial/profilePics/profile1.jpg" method="post" enctype="multipart/form-data">
```
2. Spring Content requires the uploaded file to be sent with the name `file`, not `attachment` so I updated the `input type=file` also in `index.jsp` to `name="file"`, as follows:- 

```
    <input type ="file" name ="file">
```
3. Because of where the ProfilePicStore interface is placed in the project I updated the `@EnableFilesystemStores` annotation as follows:-

`@EnableFilesystemStores("com.ahmed.mostafa.controllers")`

4. I update the filesystemRoot to be outside of the webapp.  As I am on a mac in my case it was `/tmp/websocial`.  I would advise that you dont put it inside the web app because - whilst the war may be exploded onto the filesystem - and whilst you may be able to detect where this is - I dont think app server provide any guarantees that this location will be stable from one deployment to the next; i.e. it may well change when you deploy the next version of you webapp.  At the same time I presume you will be want profile pictures and associated profiles to persist across deployments so I would therefore recommend you store the images outside of the webapp.  The profile pictures dont need to be retrieved using resource mappings and in fact they can be retrieved using the same URL as the form's action so I put an image tag of the page, as follows:

`<img src=/websocial/profilePics/profile1.jpg` 

Let me know if this makes sense.  If you have issues I can check my updated version into github or something.  I will also update the SO post as well.  

HTH

**Comment by AhmedMohsenM95** [comment]
Hello @paulcwarren , i thank you for helping me so far , i went and made all the changes you said here and even followed what you said in the updated SO post but still i get the same error , i uploaded the photo for you too see , i even uploaded the project again after updating it with what you said.

Maybe i've done something wrong, BTW i use Tomcat 9 server integrated with intellij if that will make any difference.
 
![error](https://user-images.githubusercontent.com/39065439/41089146-6b24f7e2-6a41-11e8-9a04-87c06cbba1d9.png)
 
and here is the updated project

[upload-updated](https://ufile.io/l5k4h)

**Comment by paulcwarren** [comment]
Whoops...there was a typo in my response.  In SpringWebConfig, the `@EnableFilesystemStores` should be this:

`@EnableFilesystemStores("com.ahmed.mostafa.controllers")`

and not this:

`@EnableFilesystemStores("spring.ahmed.mostafa.controllers")` 

My bad.  Sorry about that.  Try that.

**Comment by AhmedMohsenM95** [comment]
Oh , it finally worked , this was a nightmare . @paulcwarren i can't thank you enough ^ , I appreciate it this was a big help ^^

**Comment by paulcwarren** [comment]
No problem Ahmed.  Good luck with the rest of your project.
