### ISSUE TITLE
Store links - spring-content-rest expecting fully qualified links

### ISSUE THREAD

**Issue by tgeens** [paulcwarren/spring-content#386]
The explanation in the Spring Content REST docs about the Store Links does not match the 1.1.0.M4 implementation:

https://paulcwarren.github.io/spring-content/refs/release/1.1.0.M4/rest-index.html#_store_links

> Where the linkrel is named after the `@ContentId` property and the link URI is the fully-qualified URI of that content property.

I tried to reproduce the sample from the documentation and either the documentation or spring-content generates the wrong link-rel ?

Expected (per documentation):
```
"_links" : {
    "self" : {
        "href": "http://localhost:8080/dvds/1"
    },
    "dvd" : {
         "href": "http://localhost:8080/dvds/1"
    },
    "content" : {
        "href" : "http://localhost:8080/dvds/1/content"
    }
}
```

Actual:
```
"_links" : {
    "self": {
        "href": "http://localhost:8080/dvds/1"
    },
    "dvd": {
        "href": "http://localhost:8080/dvds/1"
    },
    "dvds": {
        "href": "http://localhost:8080/dvds/1"
    }
}
```

**Comment by tgeens** [comment]
Ah, the 1.0 documentation mentions fully-qualified-links - configurable with:

```
spring.content.rest.fullyQualifiedLinks=true
```

After setting this property, the expected link-rel "content" is generated.
Is it the intention to make `fullyQualifiedLinks=true` the default ?

**Comment by paulcwarren** [comment]
The intention is that fully qualified links are on by default and in fact this switch from false to true was partially based on comments that Thijs made on #148.  I had wanted to head in this direction anyway but that was good impetus.  Fully qualified links is part of a larger feature to support multiple content properties per entity. 

Anyway, fully qualified links are in fact on by default when using `spring-content-rest` directly but `spring-content-rest-boot-starter` overrides that back to false which is the actual bug here.
