### ISSUE TITLE
Can't config "Cache-Control" header for spring-content

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#503]
Can't config "Cache-Control" header for spring-content, It's alway return "Cache-Control: no-cache, no-store, max-age=0, must-revalidate" , even I configed with spring.resources.cache.cachecontrol.max-age=300s

**Comment by paulcwarren** [comment]
Thanks @lmtoo looks like we could add the ability to configure `HandlerInterceptor`'s fairly easily BUT playing about with them it seems that only `preHandle` methods are effective at adding headers.  `afterCompletion` and `postHandle` don't work - presumably because the `ResourceHttpRequestHandler` ultimately flushes the response.  

I'll look at bit more and see if there is a better way to do this.

**Comment by paulcwarren** [comment]
Hey @lmtoo, 

I assume you are using Spring Security?  I just wanted to let you know that Spring Security will, by default, turn caching off.  Probably the reason you are getting those header values back?

I also believe the `spring.resources.cache.cachecontrol.max-age` property is probably for configuring the cache values of static resources. 

Do you just want to define cache values for each of your Store's `getContent` methods?

**Comment by lmtoo** [comment]
Yes, I'm using Spring Security, define cache values for each Store is ok.

**Comment by paulcwarren** [comment]
Hi @lmtoo, I've finally got to this.  Can you take a look at this docs snippet and see if this satisfies your requirements please?  

<img width="1022" alt="Screen Shot 2021-05-04 at 11 08 32 PM" src="https://user-images.githubusercontent.com/7402112/117102741-ce3a6880-ad2d-11eb-9c37-f1de82297ede.png">
