### ISSUE TITLE
Getting contentStore bean not found error on startup

### ISSUE THREAD

**Issue by mmoukimou** [paulcwarren/spring-content#599]
Hi Paul,

I was using spring content with local file system. that was working just fine. now preparing to deploy my application to aws. created a profile for aws and added spring content for s3. but when i run the app now, it fails with the following error: ***************************
APPLICATION FAILED TO START
***************************

Description:

Field cvExportTemplateFileStore in com.codefield.resumemanager.service.ResumesTemplateParser required a bean of type 'com.codefield.resumemanager.repository.CvExportTemplateFileStore' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'com.codefield.resumemanager.repository.CvExportTemplateFileStore' in your configuration. Am i missing something? I am running it on eclipse

**Comment by mmoukimou** [comment]
found out after debugging that the error might be happening when i add  this dependancy 
```
<dependency>
			<groupId>com.github.paulcwarren</groupId>
			<artifactId>content-s3-spring-boot-starter</artifactId>
			<version>1.1.0.M5</version>
		</dependency>
```

**Comment by paulcwarren** [comment]
Hi @mmoukimou ,

In addition to the changes you called out did you add an AmazonS3 client bean and configure your bucket?  There are more details [here](https://paulcwarren.github.io/spring-content/refs/release/1.1.0.M5/s3-index.html#_s3_content_stores) in case that is useful.

**Comment by mmoukimou** [comment]
I have done all that. but still getting the error. it looks like it is not possible to use both packages. I have to switch each time.

plus now i am getting this error too: 6:09:48.710 [restartedMain] ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field client in internal.org.springframework.content.s3.config.S3StoreFactoryBean required a single bean, but 2 were found:
	- s3Client: defined by method 's3Client' in class path resource [internal/org/springframework/content/s3/boot/autoconfigure/S3ContentAutoConfiguration.class]
	- amazonS3: defined in null

Trying to find the duplicate, but it is nowhere to see. what might be the cause of this too?

**Comment by paulcwarren** [comment]
Spring Content supports using multiple stores at the same time  but to do this you need to extends the store-specific interfaces; `S3ContentStore`, `FilesystemContentStore`.

1.2.x code line (requires Spring Boot 2.4.x) also supports switching between stores (dev/test type scenarios) by configuring a `spring.content.storage.type.default` property.

I am not sure where that other bean is coming from.  Neither does the f/w by the looks...`defined in null`.  But that does look odd because the autoconfiguration is configured to create that bean [only if missing](https://github.com/paulcwarren/spring-content/blob/603de2734f7189d98d66ec6d0f21478487f94780/spring-content-autoconfigure/src/main/java/internal/org/springframework/content/s3/boot/autoconfigure/S3ContentAutoConfiguration.java#L28).

There is an s3 boot started example [here](https://github.com/paulcwarren/spring-content-examples/blob/5e5e8cf249fadc5282e8f2f42c72391a51d7158e/spring-eg-content-s3-boot-starter/src/test/java/examples/s3/S3BootExamplesTest.java) that might help?

If you can create a project that reproduces the project, push it to github and point me at it I can investigate for you?

**Comment by paulcwarren** [comment]
Hi @mmoukimou , are you still having issues, or were we able to resolve them?

**Comment by mmoukimou** [comment]
Hi @paulcwarren yes I am. it looks like including both the content-s3-spring-boot-starter and the 'fs' dependancies, is creating an issue that is preventing spring from starting the application. I have to use either one or the other in order to start the app. I took a look at the documentation but nothing there is helping me as there is no case with both dependancies included in one app.

**Comment by paulcwarren** [comment]
Ok.  Thanks for getting back to me.  Let's me try and repro this.  So, you are using 1.1.x codeline and using the store-specific S3ContentStore and FilesystemContentStore interfaces?

**Comment by paulcwarren** [comment]
Hi @mmoukimou, give [this sample project](https://github.com/paulcwarren/multi-store-example/tree/33b738cf1a400d92ba30d3282bb183aa3f500388) a look.  Demonstrates how to have switchable stores based on a property in application.properties.  Is this the sort of thing you are looking for?

**Comment by mmoukimou** [comment]
Yes @paulcwarren it looks like a good example i will try it out locally and let you know what ever the result is.

Thank you !

**Comment by paulcwarren** [comment]
@mmoukimou any luck?

**Comment by mmoukimou** [comment]
Hi @paulcwarren,

Thank you for this example.  It looks now like everything is working. at least, the app is starting now. I will spend more time testing later. But I think that we can close this issue for now.
