### ISSUE TITLE
Error starting app with S3ContentStore and aws-messaging dependencies

### ISSUE THREAD

**Issue by arkaitzosa** [paulcwarren/spring-content#622]
Hi,

I am using S3ContentStore in my spring boot app with no problems until I added aws-messaging dependency to access amazon sqs service.

Now I have an error at startup:

```
Parameter 1 of constructor in internal.org.springframework.content.s3.config.S3StoreFactoryBean required a single bean, but 2 were found:
	- s3Client: defined by method 's3Client' in class path resource [internal/org/springframework/content/s3/boot/autoconfigure/S3ContentAutoConfiguration.class]
	- amazonS3: defined in null
```

I am using Spring Boot 2.4.5 and Spring Content 1.2.4

The dependency I am adding is:

```
<dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-starter-aws-messaging</artifactId>
</dependency>
```

In dependencyManagement section you need to add this:

```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>2.3.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
</dependencyManagement>
```

Thanks!

**Comment by paulcwarren** [comment]
I successfully reproduced this today.  My best guess is that spring-cloud-aws is creating the AmazonS3 bean and your application is now creating a second bean.

If you are not using `spring-content-s3-boot-starter` then I think you could try one of two things:

- remove the `AmazonS3` bean you are creating in your config.  You no longer need it as spring-cloud-aws with create it
- or, mark yur bean as `@Primary` so that the application context knows to use your bean and forget the aws one

If you are using `spring-content-s3-boot-starter` then we need to investigate further because spring contnet's autoconfiguration only instantiates the bean if it is missing which I think means that spring-cloud-aws is doing something funky and it cant be seen by spring boot autoconfiguration's @OnMissingBean annotation.  LMK

**Comment by arkaitzosa** [comment]
Yes, I am using `spring-content-s3-boot-starter`, I am not creating any bean in my application.

**Comment by paulcwarren** [comment]
OK.  I will try and investigate why these two dont play well together then.  Its interesting, actually, because we do tell Spring Boot to not create the bean if already there.  It's almost like aws messaging is not playing by proper spring boot rules but, as I say, will investigate.
