### ISSUE TITLE
@OneToMany relation

### ISSUE THREAD

**Issue by mouradneb** [paulcwarren/spring-content#69]
Hi,

Spring content never return results with @OneToMany relationship. Even with Jpa and Mongodb database.

Can i get more details for this kind of relationship.

Thx a lot.

**Comment by paulcwarren** [comment]
Hi @mouradneb,

Thanks for giving Spring Content a try.  What exactly are you trying to do?  Associate multiple pieces on content with a single @Entity/@Document?  If not, can you provide an example of what is not working.

Thanks

**Comment by mouradneb** [comment]
Thx Paul for your quick response,

I read your test code in:
\spring-content-master\spring-content-rest\src\test\java\internal\org\springframework\content\rest\...

and I tried to associate one entity or document with list of objects, as given in your test code like this:

Exmaple 1:
@Entity
@Data
@AllArgsConstructor @NoArgsConstructor
public class TestEntity2 {
	private @Id @GeneratedValue Long id;	
	private  @RestResource @OneToMany(fetch = FetchType.EAGER,cascade = CascadeType.ALL) List<TestEntityChild> children ;
}

or this :

@Entity
//@EntityListeners(AuditingEntityListener.class)
@Data
@AllArgsConstructor @NoArgsConstructor
public class TestEntity2 {
	private @Id @GeneratedValue Long id;	
	private  @RestResource @ElementCollection(fetch = FetchType.EAGER) List<TestEntityChild> children ;
}

in my repository i have this:

@RepositoryRestResource(path = "parent")
public interface TestEntity2Repository extends JpaRepository<TestEntity2, Long> {
}

if path of content store is definied to"child" like  below, restful get command never return object by typing url = 
{parent}/{parentid}/{child}/{contentid}

@ContentStoreRestResource(path = "child")
public interface TestEntityChildContentRepository
		extends ContentStore<TestEntityChild, UUID>, Renderable<TestEntityChild> {
}

but if i put parent in @ContentStoreRestResource(path = "parent"), it will return child object correctly, but never parent by url={parent}/{parentid}.

i can give u more details if u want and i'm very sorry for my bad english :o)

thx a lot for your time

**Comment by paulcwarren** [comment]
Hi @mouradneb.  

I think I see what you are trying to do.  `TestEntity2` is a little confusing.  I have been meaning to clean all of that test code up but not got around to it yet.

So, for reference, the test that uses that entity is [here](https://github.com/paulcwarren/spring-content/blob/master/spring-content-rest/src/test/java/internal/org/springframework/content/rest/controllers/ContentPropertyRestControllerIntegrationTest.java).  Specifically, you probably want to look at [this spec](https://github.com/paulcwarren/spring-content/blob/9edafc92db6d8d7145efaadecf9c673e127fd8ac/spring-content-rest/src/test/java/internal/org/springframework/content/rest/controllers/ContentPropertyRestControllerIntegrationTest.java#L396).

If you are interested in having a collection of content streams associated you probably want to configure your content store for `TestEntityChild` as follows:

```
@StoreRestResource(path = "parent")
public interface TestEntityChildContentRepository extends ContentStore<TestEntityChild, String> {
}
```

This will export the store into the same URI space as the "owning" `TestEntity2Repository` which then means you can then address content in the collection as follows:

`curl http://localhost:8080/parent/{testEntity2Id}/children/{testEntityChildId}`

The rationale here is that because content is associated with a "sub" entity; i.e. content is really associated with `TestEntityChild`class - that's where the `@ContentId` annotation is, not `TestEntity2`, and these "sub" entities are stored in a (collection) field called `children`, you locate that content through the parent entity using the name of the "content" field; i.e. "children" in this case. 

HTH

**Comment by mouradneb** [comment]
Hi Paul,

Thx for help,

I added one level by replacing "parent" class with "root" class which include parent by @OneToOne relationship.

By having @ElementCollection List of "child" in "parent", now i can get what i'm looking for.

Thx Paul again.

**Comment by paulcwarren** [comment]
OK.  Glad we figured it out. Are you happy for me to close this issue?

**Comment by mouradneb** [comment]
Thx a lot Paul, 

I'll glad we still in touch, because, i'm EMC Customer for VNX, NETWORKER, DATADOMAIN and now ISILON, and i use springboot just for fun.

Thx again paul.

**Comment by paulcwarren** [comment]
Likewise.  

Well, please keep Spring Content in mind especially when your company next decides it needs an application that handles documents and wants to deploy to PCF or PKS :-)
