### ISSUE TITLE
Resource Not Found

### ISSUE THREAD

**Issue by JankDev** [paulcwarren/spring-content#70]
Hello,
I've been playing around with spring content lately but I can't figure out why I'm getting this error.
![notfound](https://user-images.githubusercontent.com/41518032/56458114-e6c3ca00-6382-11e9-90b9-66e3f307a66d.png)
If I use a normal controller the resource gets detected but with content rest it gets not.
I've annotated my config class with EnableFileSystemStores and defined a filesystem bean, exactly like in the getting started guides, but it isn't working.Here the code for the store
`@Component
@StoreRestResource
public interface BookContentFileStore extends ContentStore<BookContentFile, UUID> {
}`

I access the endpoints created by spring data rest and I see that the content store endpoint got exposed but the file cannot be found.
What can I do?

**Comment by paulcwarren** [comment]
Hi @JankDev , thanks for taking Spring Content for a spin.  

That sounds a little odd.  If you can see the `link` in the payload you get back from the Spring Data REST endpoint for the entity you are associating the content with then it sounds like everything is being enabled.

I assume you are getting no errors in the console log from the application?

Can you let me have a look at the `BookContentFile` class?  Or better still, commit a project that shows the problem in your Github org and point me at it?

**Comment by JankDev** [comment]
Thanks for your reply.
Here it is [https://github.com/JankDev/PowiescAPI](url).

**Comment by paulcwarren** [comment]
Hi @JankDev,

Thanks for the project.  That was very helpful.  I think I see what is happening.  

In terms of addressability of the content, there are a couple of ways to achieve coordinated entity/content REST endpoints.  The original intent, from a Spring Content perspective (and what is reflected in the PR I made to you), is to export the `BookContentFileStore` interface into the same URI space as the Spring Data repository with: 

`@StoreRestResource(path="books")`.

This then makes the Spring Data entity addressable at:

`/books/{id}` 
(NB: it is important that you specify the `Accept: application/hal+json` header on that request otherwise the content controllers will grab it and fail).

and the content addressable at:

`/books/10/file/{contentId}`

We call this "property association" in [our docs](https://paulcwarren.github.io/spring-content/refs/snapshot/fs-index.html#_patterns_of_content_association).  Addressing the content this way supports `GET`, `PUT` and `DELETE`.  It will also automatically handle the creation and association of the `BookContentFile` entity instance if it needs to.  Given you didn't create a repository for `BookContentFile` I assume this is what you would want.

But you could also NOT specify the `path` on the `BookContentFileStore` interface and that means book entities would still be addressable at:

`/books/{id}` 

as before.  But store would be exported and addressable at:

`/bookContentFiles/{id}`  

However, for this to work you would need to create a repository for the BookContentFile and handle creating and associating these "sub" entities with parent book entities yourself.  I presume this is not what you want as it will be a chattier REST API.
 
So accepting the PR should fix your issue but I suspect, given a few people have raised this issue, our documentation needs some improvement.  I also noticed that we are actually injecting several contnet links in the Spring Data responses

**Comment by JankDev** [comment]
Thank you, I'm grateful.
Yes the Accept Header have made it all working.
I noticed that too,there is a link to the original book in the file payload but when clicking on it, it of course triggers a conversion error.

But all is working for now so this issue can be closed.

Thanks!

**Comment by paulcwarren** [comment]
OK.  I'll verify the link issues and raise those separately.  Did you see [my PR](https://github.com/JankDev/PowiescAPI/pull/2) too?  Just checking to make sure you got it.

**Comment by JankDev** [comment]
Yes I got it, thanks.
I've also asked a question on gitter btw.

**Comment by paulcwarren** [comment]
Thanks for the heads-up.  My notification settings were messed up so I didnt get a notification.
