### ISSUE TITLE
annotated @Version  Entity can't set @ContentId、@MimeType、@OriginalFileName automatically

### ISSUE THREAD

**Issue by lmtoo** [paulcwarren/spring-content#79]
hi，I have a bug to report.
ContentEntityRestController's handleMultipart first find domainObj from JpaRepository，
and then set @ContentId、@MimeType、@OriginalFileName value to the domainObj,
and then check domainObj whether annotated  @Version,if so find domainObj from JpaRepository again , but the domainObj changed ,don't have these value anymore , it seems persistence context changed.

**Comment by paulcwarren** [comment]
Hi lmtoo,

Thanks for raising this issue.

I agree [this code](https://github.com/paulcwarren/spring-content/blob/b08799907e7a980a2fceeb48b6f69dce7bac24d3/spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/ContentEntityRestController.java#L233) looks a little weird.  

If I recall this is because `ContentStore.setContent` should return the entity but *doesn't*.  This is a problem when @Version is applied to the entity.  Hibernate will update it during save/persist and return the updated entity with the updated version field that setContent drops on the floor.   If we dont re-fetch the entity then the subsequent save fails.  I believe this works though because the re-fetch just grabs the (updated) entity out of its cache, rather than going back to the database.  But, I could be wrong.

Is this failing for you?  And also what Spring Boot stack are you on?  2.1, or 2.2?
