### ISSUE TITLE
How to use this to support video streaming?

### ISSUE THREAD

**Issue by wu162** [paulcwarren/spring-content#86]
I find this repo through [https://stackoverflow.com/questions/48201031/restful-based-video-streaming](https://stackoverflow.com/questions/48201031/restful-based-video-streaming). But I can't figure out where should I put my videos and how to set the path.Can someone explain in detail?

**Comment by paulcwarren** [comment]
Let's say you want to store your files in `/var/files`.

If you use the spring boot starters then you can do one of several things to specify this location:

1. Set the environment variable `SPRING_CONTENT_FS_FILESYSTEM_ROOT` to `/var/files`
2. In your `application.properties`, set the property `spring.content.fs.filesystem.root` to `/var/files`
3. Add the following bean to your application's configuration:

```
    @Bean
    FileSystemResourceLoader fileSystemResourceLoader() {
        return new FileSystemResourceLoader(`/var/files`);
    }
```
4. Don't set anything and let spring content choose a location under java tmpdir which is reported in the startup logs (good for testing but not for production obviously):

`2019-11-17 21:53:29.955  INFO 33522 --- [           main] o.s.c.fs.io.FileSystemResourceLoader     : Defaulting filesystem root to /var/folders/7v/518b18d97_3f4c8fzxphy6f8zcm51c/T/3971232271951242717
`

If you dont use the spring boot starters and use the storage module dependencies directly; i.e. depend on `spring-content-fs`, rather than `spring-content-fs-boot-starter`, then you can do one of several things to specify this location:

1. Add the following bean to your application's configuration:
```
    @Bean
    FileSystemResourceLoader fileSystemResourceLoader() {
        return new FileSystemResourceLoader(`/var/files`);
    }
```
2. Don't set anything and let spring content choose a location under java tmpdir which is reported in the startup logs (again good for testing but not for production obviously).  

Does that clarify things?

**Comment by wu162** [comment]
Thank you! It's very useful!

> Let's say you want to store your files in `/var/files`.
> 
> If you use the spring boot starters then you can do one of several things to specify this location:
> 
> 1. Set the environment variable `SPRING_CONTENT_FS_FILESYSTEM_ROOT` to `/var/files`
> 2. In your `application.properties`, set the property `spring.content.fs.filesystem.root` to `/var/files`
> 3. Add the following bean to your application's configuration:
> 
> ```
>     @Bean
>     FileSystemResourceLoader fileSystemResourceLoader() {
>         return new FileSystemResourceLoader(`/var/files`);
>     }
> ```
> 
> 1. Don't set anything and let spring content choose a location under java tmpdir which is reported in the startup logs (good for testing but not for production obviously):
> 
> `2019-11-17 21:53:29.955 INFO 33522 --- [ main] o.s.c.fs.io.FileSystemResourceLoader : Defaulting filesystem root to /var/folders/7v/518b18d97_3f4c8fzxphy6f8zcm51c/T/3971232271951242717 `
> 
> If you dont use the spring boot starters and use the storage module dependencies directly; i.e. depend on `spring-content-fs`, rather than `spring-content-fs-boot-starter`, then you can do one of several things to specify this location:
> 
> 1. Add the following bean to your application's configuration:
> 
> ```
>     @Bean
>     FileSystemResourceLoader fileSystemResourceLoader() {
>         return new FileSystemResourceLoader(`/var/files`);
>     }
> ```
> 
> 1. Don't set anything and let spring content choose a location under java tmpdir which is reported in the startup logs (again good for testing but not for production obviously).
> 
> Does that clarify things?

Thank you! It's very useful!

**Comment by paulcwarren** [comment]
Did this get you into a working state @wu162 ?

**Comment by paulcwarren** [comment]
Ping

**Comment by paulcwarren** [comment]
Closing as I think this has resolved your issues.   Please feel to re-open if not.
