### ISSUE TITLE
JPA: Get content within a transaction

### ISSUE THREAD

**Issue by JoeBrig** [paulcwarren/spring-content#89]
Is it possible to read the content of a new file within a transaction that also created the content?  

I working with an InputStream from a browser that I place in the database.  I also need to generate an MD5, so I'm trying to read the content after setting it, but I'm getting a null InputStream.  I will use the MD5 value before ending the transaction.  My business rule tests for duplicates in some cases. 
 
 Currently:  
1. Create the file entity
2. Save the entity.  "not sure why I have call save here but 3 does not work without calling saving."
3. ContentRepository.setContent
4. ContentRepository.getContent .  returns null

Using: 1.0.0.M3, spring boot 2.2.1, mysql 8

**Comment by paulcwarren** [comment]
Hi @JoeBrig 

A couple of questions:
- when making the `getContent` are you using an event handler? 
- are you using Versioning; i.e. spring-versions-jpa?

**Comment by JoeBrig** [comment]
Hello,

I’m not using an event handler or spring-versions-jpa.  I do have a @Version in they Entity.  

Everything is in a @Service @Transactional class.  When removing the @Transactional  the getContent returns the expected value. 

I’ve created a simple test project, but its working fine with getContent returning the InputStream as expected,, so tomorrow I’ll try and determine the difference between the two projects. 

Thanks,
Joe

**Comment by JoeBrig** [comment]
I was able to create a test project that demonstrates the issue.  The combination for using @Transactional, Mysql, and making a repo call in the method results in getContent returning null.  Sample project attached.

[sctran-test.zip](https://github.com/paulcwarren/spring-content/files/3886955/sctran-test.zip)

```
@Service
@Transactional

public class DocumentService {

    public void loadDocument(String fileName, InputStream inputStream ) {

        // The next line, with mysql + transactional, causes getContent below to return null
        documentRepo.findAll();

        Document document= new Document();
        document.setFileName(fileName);
        document = documentRepo.save(document);

        documentContentRepo.setContent(document,inputStream);

        InputStream content = documentContentRepo.getContent(document);
        System.out.println(content);

    }
```

**Comment by Dominik128** [comment]
I have the same problem. With Spring Content FS setContent and getContent on the same entity in one transaction works perfectly. However with Spring Content JPA, getContent always returns null. When I perform the same code without the @Transactional over the method it works perfect. Are there any workarounds?

**Comment by paulcwarren** [comment]
Hi @Dominik128, thanks for letting me know this is an issue for you too.  

As far as I am aware there are no known workarounds. 

I did a little bit on investigation and I came to the conclusion that the blob resource implementation needs to be updated to use the `TransactionTemplate`, rather than the invoke transactions through the `JdbcTemplate` as it does today.  This, I believe, will allow it to participate in transactions started by any higher level `@Transactional` service methods, as in both of your cases.

So, this could be a relative quick change.  But I apologize for the delay.  I have been pre-occupied with family matters for the last few weeks but getting back into things now.  Since, there are multiple folks interested in this I will prioritize it and look at it next.
