### ISSUE TITLE
[Info] Data Rest: mechanism to redirect request to spring data rest or spring content based on Content-Type

### ISSUE THREAD

**Issue by gianx89** [paulcwarren/spring-content#915]
Hi, I really love your work and library and I'm intestered in studying its inner mechanisms.

Can you point to me the files that I should look at and study to understand how you manage to redirect request to spring data rest or spring content based on Content-Type?

Can you give me some info about it?

Thank you in advance

**Comment by paulcwarren** [comment]
Hi @gianx89, 

Essentially, Spring Content REST registers an `@Controller` called [StoreRestController](https://github.com/paulcwarren/spring-content/blob/f800cacc6f46ea06a74ace7773c7e87874a44605/spring-content-rest/src/main/java/internal/org/springframework/content/rest/controllers/StoreRestController.java) with a highest precedence than Spring Data REST's so Spring Content's REST layer gets to handle request before Spring Data.  I actually wanted to put Spring Content REST's controller at a lower precedence and let Spring Data REST handle or pass but that runs contrary to Spring Data REST's architecture so I couldn't do that.  

Spring Content REST and Spring Data REST, by default, live in the same URI space; i.e. `/myentities`.  You can configure this but by default this is how it is.   However, "content" is associated with entities using primitive-typed, annotated fields that are not usually handled by Spring Data REST.  That is to say that, generally speaking, content properties exist in the spaces left by Spring Data REST.  

So, when using fully-qualified URIs to fetch content; i.e. `/myentities/1/content` Spring Data REST would not handle this anyways (because the "content" field is really just a primitive-typed field on the entity).  Therefore, Spring Content REST can handle it without too many worries.

For backward-compatibility reasons though if an entity has just a single content property then its possible to request something like `/myentities/1` - what I call a shortcut URI -  and then it depends on the accepted content type whether, or not, Spring Content REST will handle it, or leave it alone for Spring Data REST to handle.  That decision-making is handled [here](https://github.com/paulcwarren/spring-content/blob/f800cacc6f46ea06a74ace7773c7e87874a44605/spring-content-rest/src/main/java/internal/org/springframework/content/rest/mappings/ContentHandlerMapping.java#L108).

HTH
