### ISSUE TITLE
Transaction support for JPA store

### ISSUE THREAD

**Issue by javolek** [paulcwarren/spring-content#92]
Is there a way to configure the transaction support for JPA store?

I've noticed that that if I run my integration tests on a clean DB with transaction set on rollback, the `BLOB` table stay populated after that rollback. I've try to investigate why and I found that the content setting code is run in another thread which forces new transaction creation, that will be usually committed independent of the outcome of the transaction in main thread.

May be I'm just missing something, but if not then how is the content store supposed to work in the transaction context?

**Comment by paulcwarren** [comment]
Short answer, No.  

Longer answer.  We decided to support Spring's Resource API early on (before the JPA module really existed).  Basically, a Store is a `ResourceLoader` that can hand back Resources (that, in addition to standard Spring Resources, can also be deleted).

This meant that we had to jump through a few hoops when it came to the JPA module as we have to make InputStream's into OutputStream's and vice versa.  We used PipedInput/OutptutStreams and threads for this.  We did also try using the filesystem as the temporary store but it was quite slow compared to the piped streams.  But, if there are complications with transactions, then perhaps we have to go back to this approach?

I am about to do some investigation in this exact area for [issue 89](https://github.com/paulcwarren/spring-content/issues/89) so I will investigate this at the same time.

**Comment by javolek** [comment]
Hello Paul, thanks for the quick response. I've just implemented simple workaround, but it may also be a good last resort idea. What I do is that for each file that is stored in the transaction I register `TransactionSynchronizationAdapter` with `TransactionSynchronizationManager` and override `afterCompletion` method with code that deletes that file if the transaction is rolled back.

Anyway, as far as the new thread is created only for the sake of the piped stream then there must be another solution I think. I would also try look into it.

**Comment by paulcwarren** [comment]
That would be great.

**Comment by javolek** [comment]
I've done some investigation and I found out that JDBC features a [Blob](https://docs.oracle.com/javase/7/docs/api/java/sql/Blob.html) class with `Blob::setBinaryStream` method that provides an `OutputStream` that can be written to. As far as I understand the documentation [here](https://docs.oracle.com/javase/tutorial/jdbc/basics/blob.html) we can create `Blob` and return it wrapped in the custom `OutputStream` implementation, which when closed prepares the necessary statements, sets the blob and executes that statement. This should actually all work without the need of another thread. @paulcwarren, is this the way to go?

**Comment by paulcwarren** [comment]
Looking at the code again I don't think it is as simple as flipping the threads, sadly, because `AbstractBlobResource.getOutputStream` has to return something so I am not even sure what it would return if we were trying to do the insert/update in the current thread.

We tried the "write on close" approach that you describe before and because we had to stream via a file - in order to prevent OOM for very large files - it was very slow.  And in fact what led us to the piped input stream in the first place.  

So, I am now thinking we should try returning a "buffered writing" OutputStream from `AbstractBlobResource.getOutputStream`.  This new class would append content to the database blob every time the internal write buffer filled up.  This would prevent OOMs and would be about as efficient, in terms of speed, as we could get.  

The only other reservation I have is I remember when I worked on this first time around the jdbc driver blob implementations are very patchy.  We currently support HSQL, H2, MySql, Postgres and SqlServer so fingers crossed we get lucky that the various jdbc drivers implement enough of Blob to support the above implementation.

**Comment by javolek** [comment]
Just for the sake of completeness, there is also a possibility to use [updatable cursors](https://docs.oracle.com/javase/tutorial/jdbc/basics/retrieving.html). I think this would allow us to use the piped streams but to perform the SQL-Statements in current thread. Still I would rather prefer to use Blobs either with updatable cursor or with set-on-close solution as far as possible and as far as the performance would not suffer. Also I'm not sure how does the support for updatable cursors looks like when compared with blobs.
